[package]
name = "solana-ed25519-sha512"
description = "An optimized SHA-512 implementation for onchain Solana Ed25519 verification"
authors = ["Dean Little <@deanmlittle>"]
version = "0.1.2"
edition = "2021"
license = "MIT"


[lib]
crate-type = ["lib", "cdylib"]

[dependencies]